# Development environment
spring:
  profiles:
    active:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql : true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

path:
  upload-images: '/Users/ich/Downloads/'
